
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 18:47:51 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int CHAR = 50;
  public static final int CONST = 7;
  public static final int GE = 35;
  public static final int IMPL = 11;
  public static final int CONTINUE = 43;
  public static final int LPAREN = 16;
  public static final int SEMI = 18;
  public static final int MINUS = 27;
  public static final int RPAREN = 17;
  public static final int AND = 30;
  public static final int LT = 36;
  public static final int OR = 31;
  public static final int BOOL = 48;
  public static final int COMMA = 21;
  public static final int CLASS = 44;
  public static final int INC = 28;
  public static final int DIV = 24;
  public static final int PLUS = 26;
  public static final int IF = 38;
  public static final int ASSIGN = 8;
  public static final int THIS = 46;
  public static final int DOT = 20;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int RBRACKET = 15;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 49;
  public static final int MOD = 25;
  public static final int NEQ = 33;
  public static final int IDENT = 51;
  public static final int BREAK = 42;
  public static final int VOID = 4;
  public static final int EQ = 32;
  public static final int FOREACH = 10;
  public static final int COLON = 19;
  public static final int ELSE = 39;
  public static final int LBRACE = 12;
  public static final int ENUM = 9;
  public static final int READ = 6;
  public static final int WHILE = 41;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 45;
  public static final int PROG = 2;
  public static final int DEG = 22;
  public static final int DEC = 29;
  public static final int GT = 34;
  public static final int DO = 40;
  public static final int PRINT = 5;
}

